# Generated by Django 5.1.2 on 2024-11-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
