# Generated by Django 4.2.16 on 2024-11-13 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventorganizer_alter_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtag',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventtag'),
        ),
    ]
