# Generated by Django 4.2.16 on 2024-11-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_eventtag_events_event_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tag',
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.eventtag'),
        ),
    ]
