# Generated by Django 5.1.2 on 2024-11-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
