name: Django CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: eventmaster_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Migrations
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/eventmaster_test
        DJANGO_SETTINGS_MODULE: event_management_system.settings
      run: python manage.py migrate

    - name: Run Tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/eventmaster_test
        DJANGO_SETTINGS_MODULE: event_management_system.settings
      run: |
        python manage.py test